app/reclamation/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, TextAreaField, validators
from wtforms.validators import DataRequired
from wtforms.fields.html5 import DateField, DateTimeField
from wtforms_sqlalchemy.fields import QuerySelectField
from wtforms_components import read_only

from app import db
from app.models import Customer, PartNo, Reclamation


class ReclamationForm(FlaskForm):
    customer = QuerySelectField(
        "Customer",
        query_factory=lambda: db.session.query(Customer).order_by("name"),
        get_pk=lambda a: a.id,
        get_label=lambda a: a.name,
        allow_blank=True,
    )

    informed_date = DateField("Informed Date", format="%Y-%m-%d")
    due_date = DateField("Due Date", format="%Y-%m-%d")
    part_model = QuerySelectField(
        "Part Model",
        query_factory=lambda: db.session.query(PartNo).order_by("model"),
        get_pk=lambda a: a.id,
        get_label=lambda a: a.model,
        allow_blank=True,
    )
    part_sn = StringField("Serial Number")
    part_prod_date = DateField("Part Production Date", format="%Y-%m-%d")
    description = TextAreaField("Description of the issue")

    submit = SubmitField("Create a claim")


class EditReclamationForm(FlaskForm):
    customer = QuerySelectField(
        "Customer",
        query_factory=lambda: db.session.query(Customer).order_by("name"),
        get_pk=lambda a: a.id,
        get_label=lambda a: a.name,
        allow_blank=True,
    )

    informed_date = DateField("Informed Date", format="%Y-%m-%d")
    due_date = DateField("Due Date", format="%Y-%m-%d")
    part_model = QuerySelectField(
        "Part Model",
        query_factory=lambda: db.session.query(PartNo).order_by("model"),
        get_pk=lambda a: a.id,
        get_label=lambda a: a.model,
        allow_blank=True,
    )
    part_sn = StringField("Serial Number")
    part_prod_date = DateField("Part Production Date", format="%Y-%m-%d")
    description = TextAreaField("Description of the issue")
    finished_date = DateTimeField(
        "Finished Date",
        format="%Y-%m-%d %H:%M",
        validators=[validators.Optional()],
        render_kw={"readonly": True},
    )

    submit = SubmitField("Edit the claim")


class ReadOnlyReclamationForm(EditReclamationForm):
    def __init__(self, *args, **kwargs):
        super(ReadOnlyReclamationForm, self).__init__(*args, **kwargs)
        read_only(self.customer)
        read_only(self.informed_date)
        read_only(self.due_date)
        read_only(self.part_model)
        read_only(self.part_sn)
        read_only(self.part_prod_date)
        read_only(self.description)
        read_only(self.finished_date)


class CloseReclamationForm(FlaskForm):
    submit1 = SubmitField("Close reclamation")


class ReopenReclamationForm(FlaskForm):
    submit1 = SubmitField("Re-open reclamation")


class NoteForm(FlaskForm):
    content = TextAreaField("Note", validators=[DataRequired()])
    submit2 = SubmitField("Create a note")

app/reclamation/__init__.py
from flask import Blueprint

bp = Blueprint("reclamation_bp", __name__)

from app.reclamation import routes

app/reclamation/routes.py
from flask import (
    render_template,
    flash,
    redirect,
    url_for,
    request,
    jsonify,
    current_app,
    send_from_directory,
    abort,
)
from flask_babelex import _
from flask_login import current_user, login_required
from datetime import datetime

from app import db
from app.models import PartDetails, Reclamation, PartNo, Note, File
from app.models_serialized import reclamation_schema
from app.reclamation import bp
from app.reclamation.forms import (
    ReclamationForm,
    EditReclamationForm,
    ReadOnlyReclamationForm,
    CloseReclamationForm,
    ReopenReclamationForm,
    NoteForm,
)
from app.users.notification import send_message

from werkzeug.utils import secure_filename
import os
import secrets
from string import ascii_letters
import json


@bp.route("/reclamation", methods=["GET", "POST"])
@login_required
def new_reclamation():
    form = ReclamationForm()

    if form.validate_on_submit():
        # checks if parts exists in database
        partDetails_in_database = PartDetails.query.filter_by(
            part_sn=form.part_sn.data
        ).first()
        if partDetails_in_database is None:
            newPartDetails = PartDetails(
                part_no=form.part_model.data,
                production_date=form.part_prod_date.data,
                part_sn=form.part_sn.data,
            )

        # create new claim

        new_reclamation = Reclamation(
            reclamation_requester=current_user,
            reclamation_customer=form.customer.data,
            informed_date=form.informed_date.data,
            due_date=form.due_date.data,
            reclamation_part_sn_id=partDetails_in_database
            if partDetails_in_database
            else newPartDetails,
            description_reclamation=form.description.data,
        )

        db.session.add(new_reclamation)
        db.session.commit()

        part = new_reclamation.reclamation_part_sn_id
        if part.part_no.part_no_person_in_charge:
            recepient = part.part_no.part_no_person_in_charge
            send_message(Reclamation, new_reclamation.id, recepient)

        flash("Reclamation has been added")

        reclamation = Reclamation.query.filter_by(id=new_reclamation.id).first_or_404()

        return redirect(
            url_for("reclamation_bp.reclamation", reclamation_number=reclamation.id)
        )

    return render_template("reclamation/new_reclamation.html", form=form)


@bp.route("/reclamation/<reclamation_number>", methods=["GET", "POST"])
@login_required
def reclamation(reclamation_number):
    rec = Reclamation.query.get(reclamation_number)
    requester = (
        rec.reclamation_requester.first_name + " " + rec.reclamation_requester.last_name
    )
    tickets = rec.tickets.all()
    close_form = CloseReclamationForm()
    open_form = ReopenReclamationForm()
    note_form = NoteForm()
    notes = Note.query.filter_by(rec_id=reclamation_number).all()
    files = db.session.query(File).filter_by(reclamation_id=reclamation_number).all()

    part_details = (
        db.session.query(PartDetails)
        .filter_by(id=rec.reclamation_part_sn_id.id)
        .first()
    )
    person_in_charge = part_details.part_no.person_in_charge
    users_who_can_edit = [
        rec.reclamation_requester,
        rec.reclamation_requester.team.team_leader,
        person_in_charge,
    ]

    if current_user in users_who_can_edit:

        if rec.status == 0:
            status = _("Open")
            form = EditReclamationForm(
                formdata=request.form,
                obj=rec,
                customer=rec.reclamation_customer,
                informed_date=rec.informed_date,
                due_date=rec.due_date,
                part_model=rec.reclamation_part_sn_id.part_no,
                part_sn=rec.reclamation_part_sn_id.part_sn,
                part_prod_date=rec.reclamation_part_sn_id.production_date,
                description=rec.description_reclamation,
                finished_date=rec.finished_date,
            )
            if close_form.submit1.data and close_form.validate():
                rec.finished_date = datetime.utcnow()
                rec.status = 1
                db.session.add(rec)
                db.session.commit()
                flash("Reclamation has been closed")
                return redirect(
                    url_for("reclamation_bp.reclamation", reclamation_number=rec.id)
                )
        else:
            status = _("Closed")
            form = ReadOnlyReclamationForm(
                formdata=request.form,
                obj=rec,
                customer=rec.reclamation_customer,
                informed_date=rec.informed_date,
                due_date=rec.due_date,
                part_model=rec.reclamation_part_sn_id.part_no,
                part_sn=rec.reclamation_part_sn_id.part_sn,
                part_prod_date=rec.reclamation_part_sn_id.production_date,
                description=rec.description_reclamation,
                finished_date=rec.finished_date,
            )
            if open_form.submit1.data and open_form.validate():
                rec.finished_date = None
                rec.status = 0
                db.session.add(rec)
                db.session.commit()
                flash("Reclamation has been re-opened")
                return redirect(
                    url_for("reclamation_bp.reclamation", reclamation_number=rec.id)
                )

    else:
        form = ReadOnlyReclamationForm(
            formdata=request.form,
            obj=rec,
            customer=rec.reclamation_customer,
            informed_date=rec.informed_date,
            due_date=rec.due_date,
            part_model=rec.reclamation_part_sn_id.part_no,
            part_sn=rec.reclamation_part_sn_id.part_sn,
            part_prod_date=rec.reclamation_part_sn_id.production_date,
            description=rec.description_reclamation,
            finished_date=rec.finished_date,
        )
        if rec.status == 0:
            status = _("Open")
        else:
            status = _("Closed")

    if form.submit.data and form.validate():

        # checks if parts exists in database
        partDetails_in_database = PartDetails.query.filter_by(
            part_sn=form.part_sn.data
        ).first()
        if partDetails_in_database is None:
            newPartDetails = PartDetails(
                part_no=form.part_model.data,
                production_date=form.part_prod_date.data,
                part_sn=form.part_sn.data,
            )

        # edit the claim

        rec.reclamation_customer = form.customer.data
        rec.informed_date = form.informed_date.data
        rec.due_date = form.due_date.data
        rec.reclamation_part_sn_id = (
            partDetails_in_database if partDetails_in_database else newPartDetails
        )
        rec.description_reclamation = form.description.data
        rec.finished_date = form.finished_date.data
        if rec.finished_date is None:
            rec.status = 0
        else:
            rec.status = 1
        db.session.add(rec)
        db.session.commit()
        flash("Reclamation has been edited")
        return redirect(
            url_for("reclamation_bp.reclamation", reclamation_number=rec.id)
        )

    if note_form.submit2.data and note_form.validate():
        new_note = Note(
            note_drafter=current_user, rec=rec, content=note_form.content.data
        )
        db.session.add(new_note)
        db.session.commit()
        flash("The note has been added")
        return redirect(
            url_for("reclamation_bp.reclamation", reclamation_number=rec.id)
        )

    if current_user in users_who_can_edit:
        return render_template(
            "reclamation/reclamation.html",
            form=form,
            requester=requester,
            status=status,
            rec=rec,
            tickets=tickets,
            close_form=close_form,
            open_form=open_form,
            can_edit=True,
            notes=notes,
            note_form=note_form,
            files=files,
        )
    else:
        return render_template(
            "reclamation/reclamation.html",
            form=form,
            requester=requester,
            status=status,
            rec=rec,
            tickets=tickets,
            can_edit=False,
            notes=notes,
            note_form=note_form,
            files=files,
        )


@bp.route("/all")
@bp.route("/all/<int:page_num>")
@login_required
def all_reclamations(page_num=1):
    reclamations = Reclamation.query.order_by(Reclamation.finished_date).paginate(
        page=page_num, per_page=current_app.config["ELEMENTS_PER_PAGE"], error_out=False
    )
    return render_template("reclamation/all.html", reclamations=reclamations)


@bp.route("/reclamation_get_data", methods=["GET", "POST"])
@login_required
def reclamations_data():
    reclamations = Reclamation.query.all()
    output = reclamation_schema.dump(reclamations)
    return jsonify({"reclamations": output})


@bp.route("/reclamations/all", methods=["GET", "POST"])
@login_required
def reclamations_all():
    return render_template("reclamation/reclamations_all.html")


def allowed_file(filename):
    if not "." in filename:
        return False
    extension = filename.rsplit(".", 1)[1].lower()
    return extension in current_app.config["ALLOWED_EXTENSIONS"]


def allowed_filesize(filesize):
    return int(filesize) <= current_app.config["MAX_FILE_FILESIZE"]


@bp.route("/upload_file/<int:rec_id>", methods=["GET", "POST"])
@login_required
def upload_file(rec_id):
    if request.method == "POST":
        if "file" not in request.files:
            flash("No file part")
            return redirect(request.url)
        if request.files:
            if not allowed_filesize(request.cookies.get("filesize")):
                flash("File exceeded maximum size.")
                return redirect(request.url)

app/templates/reclamation/_edit_note.html
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Open modal for @mdo</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@fat">Open modal for @fat</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Open modal for @getbootstrap</button>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>

app/templates/reclamation/_get_file.html
<div class='file-div'><a href="/get_file/{{file.relative_path|safe}}">{{ file.name }}</a>
<!-- Button trigger modal -->
    <button type="button" class="btn btn-outline-secondary btn-sm" data-toggle="modal" data-target="#modal{{file.id}}">
        <i class="fa fa-trash"></i>
    </button>

    <!-- Modal -->
    <div class="modal fade" id="modal{{file.id}}" tabindex="-1" role="dialog"
        aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{{_('Delete file')}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{_('Are you sure you want to delete this file?')}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">{{_('Cancel')}}</button>
                    <button type="button" class="btn btn-danger del-file" data-dismiss="modal" value='{{file.relative_path|safe}}'>
                        {{_('Delete')}}</button>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/reclamation/_note.html
<div class="note{{ note.id }}">
    <div class="border border-dark" style="padding: 10px">
        <b>{{ note.note_drafter.first_name }} {{ note.note_drafter.last_name }} </b>
        {{ moment(note.creation_date).format("LLL") }}

        {% if current_user == note.note_drafter or current_user == note.note_drafter.team.team_leader %}
            <button type="button" class="btn btn-outline-secondary btn-sm" data-toggle="modal"
                    data-target="#editNote{{ note.id }}"
                    data-note_content="{{ note.content }}">
                <i class="fa fa-edit"></i>
            </button>
            <button type="button" class="btn btn-outline-secondary btn-sm" data-toggle="modal"
                    data-target="#deleteNote{{ note.id }}">
                <i class="fa fa-trash"></i>
            </button>
        {% endif %}

        <hr style="margin: 0.25em">
        <div id="note_content{{ note.id }}">
            {{ note.content }}
        </div>

    </div>


    <div class="modal fade edit-note-pre" id="editNote{{ note.id }}" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edit note</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="message-text" class="col-form-label">Note:</label>
                            <textarea class="form-control" id="note-text-{{ note.id }}"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary edit-note" data-dismiss="modal" value="{{ note.id }}">
                        Edit
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteNote{{ note.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <h5>{{ _("Do you want to delete that note?") }}</h5>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary delete-note" data-dismiss="modal" value="{{ note.id }}">
                    Delete
                </button>
            </div>
        </div>
    </div>
</div>

app/templates/reclamation/_recl.html
<tr class='clickable-row' data-href={{ url_for('reclamation_bp.reclamation', reclamation_number=recl.id) }}>
    <th scope="row">{{ recl.id }}</th>
    <td>{{ recl.reclamation_customer.name }}</td>
    <td>{{ moment(recl.informed_date).format('L') }}</td>
    <td>{{ moment(recl.due_date).format('L') }}</td>
    {% if recl.finished_date is none %}
        <td>{{ _('-') }}</td>
    {% else %}
        <td>{{ moment(recl.finished_date).format('L') }}</td>
    {% endif %}
    <td>{{ recl.reclamation_part_sn.part_no.model }}</td>
    <td>{{ recl.part_sn }}</td>
    <td>{{ recl.reclamation_part_sn.production_date }}</td>
</tr>

app/templates/reclamation/all.html
{% extends 'base.html' %}

{% block app_content %}


    <div class="container">
        <h1>{{ _('Reclamations') }}</h1>
        <table class="table table-hover">
            <thead class="thead-dark">
            <tr>
                <th scope="col">{{ _('ID') }}</th>
                <th scope="col">{{ _('Customer') }}</th>
                <th scope="col">{{ _('Informed Date') }}</th>
                <th scope="col">{{ _('Due Date') }}</th>
                <th scope="col">{{ _('Finished Date') }}</th>
                <th scope="col">{{ _('Part Model') }}</th>
                <th scope="col">{{ _('Serial Number') }}</th>
                <th scope="col">{{ _('Part Production Date') }}</th>
            </tr>
            </thead>
            <tbody>
            {% for recl in reclamations.items %}
                {% include 'reclamation/_recl.html' %}
            {% endfor %}
            </tbody>
        </table>
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">

                <li class="page-item {% if not reclamations.has_prev %} disabled{% endif %}">
                    <a class="page-link"
                       href="{{ url_for('reclamation_bp.all_reclamations', page_num=reclamations.prev_num) }}"
                       aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                {% for page in reclamations.iter_pages() %}
                    {% if page %}
                        <li class="page-item"><a class="page-link"
                                                 href="{{ url_for('reclamation_bp.all_reclamations', page_num=page) }}">{{ page }}</a>
                        </li>
                    {% else %}
                        ...
                    {% endif %}
                {% endfor %}
                <li class="page-item">
                    <a class="page-link"
                       href="{{ url_for('reclamation_bp.all_reclamations', page_num=reclamations.next_num ) }}"
                       aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
        jQuery(document).ready(function ($) {
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}

app/templates/reclamation/new_reclamation.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}

    <h1>{{ _('Add Reclamation') }}</h1>

    <div class="row">
        <div class="col-md-9">
            {{ render_form(form, form_type='horizontal', horizontal_columns=('lg', 3, 9)) }}
        </div>
    </div>

{% endblock %}

app/templates/reclamation/reclamation.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/form.html' import render_field %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block app_content %}

    <div class="row">
        <div class="col-md-7">
            <h1>{{ _('Reclamation') }}</h1>
            <h3>Requester: {{ requester }} </h3>
            <h3>Status: {{ status }}</h3>

            {% if close_form %}
                {% if rec.status == 0 %}
                    {{ render_form(close_form, form_type='horizontal', horizontal_columns=('lg', 0, 1)) }}
                {% elif rec.status == 1 %}
                    {{ render_form(open_form, form_type='horizontal', horizontal_columns=('lg', 0, 1)) }}
                {% endif %}
            {% endif %}

        </div>
    </div>


    <div class="row">
        <div class="col-md-5">
            <form method="POST">
                {{ form.csrf_token() }}
                {{ render_field(form.customer, horizontal_columns=('lg', 3, 9)) }}
                {{ render_field(form.informed_date, horizontal_columns=('lg', 3, 9)) }}
                {{ render_field(form.due_date, horizontal_columns=('lg', 3, 9)) }}
                {{ render_field(form.part_model, horizontal_columns=('lg', 3, 9)) }}
                {{ render_field(form.part_sn, horizontal_columns=('lg', 3, 9)) }}
                {{ render_field(form.part_prod_date, horizontal_columns=('lg', 3, 9)) }}
                {{ render_field(form.description, horizontal_columns=('lg', 3, 9)) }}
                {{ render_field(form.finished_date, horizontal_columns=('lg', 3, 9)) }}
                {% if can_edit %}
                    {{ render_field(form.submit) }}
                {% endif %}
            </form>

            <div>
            <hr>
            <a class="btn btn-primary" role="button"
               href="{{ url_for('reclamation_bp.upload_file', rec_id=rec.id) }}">
                {{ _('Add file to reclamation') }}</a>
            {% if files %}
            <p>{{ _('Attachments:') }}</p>
                {% for file in files %}
                {% include 'reclamation/_get_file.html' %}
                    <br>
                {% endfor %}
            {% endif %}
            </div>

        </div>

        <div class="col-md-7">
            <div>
                <p><b>Tickets linked </b>
                    <a class="btn btn-primary btn-sm" role="button"
                       href="{{ url_for('ticket_bp.new_ticket', rec_id=rec.id) }}">
                        {{ _('Create new ticket') }}</a>
                </p>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Creation Date</th>
                        <th scope="col">Description</th>
                        <th scope="col">Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for ticket in tickets %}
                        {% if ticket.status == 0 %}
                            <tr class="table-danger"
                                data-href={{ url_for('ticket_bp.ticket', ticket_number=ticket.id) }}>
                                {% else %}
                            <tr class="table-success"
                                data-href={{ url_for('ticket_bp.ticket', ticket_number=ticket.id) }}>
                        {% endif %}

                    <th scope="row">{{ ticket.id }}</th>
                    <td>{{ ticket.creation_date.date() }}</td>
                    <td>{{ ticket.description_ticket }}</td>

                    {% if ticket.status == 0 %}
                        <td>Open</td>
                    {% else %}
                        <td>Closed</td>
                    {% endif %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>


            <div style="margin-top: 20px !important;">
                <p><b>Notes</b></p>
                {% for note in notes %}
                    {% include 'reclamation/_note.html' %}
                    <br>
                {% endfor %}


                <form method="POST">
                    {{ form.csrf_token() }}
                    {{ render_field(note_form.content, horizontal_columns=('lg', 3, 9)) }}
                    {{ render_field(note_form.submit2) }}
                </form>
            </div>

        </div>
    </div>

{% endblock %}



{% block scripts %}
    {{ super() }}
    <script>
        jQuery(document).ready(function ($) {
            $(".table-danger").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
    <script>
        jQuery(document).ready(function ($) {
            $(".table-success").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
    <script type="text/javascript" src="{{ url_for('static', filename='scripts/delete_file.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='scripts/edit_note.js') }}"></script>
{% endblock %}

app/templates/reclamation/upload_file.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/form.html' import render_field %}


{% block app_content %}

    <div>
        <h1>{{ _('Upload file') }}</h1>
    </div>

    <div>

        <form action="{{ url_for('reclamation_bp.upload_file', rec_id=rec_id) }}" method="post" enctype="multipart/form-data">
            <div class="form-group">
             <label>Select file</label>
            <div class="custom-file">
                <input oninput="filesize(this);" type="file" class="custom-file-input" name="file" id="file">
                <label class="custom-file-label" for="file">Select file...</label>
            </div>
            </div>

            <button type="submit" class="btn btn-primary">Upload file</button>
        </form>

    </div>

{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
    function filesize(elem){
        document.cookie = `filesize=${elem.files[0].size}`;
    }

    $('.custom-file input').change(function (e) {
        if (e.target.files.length) {
            $(this).next('.custom-file-label').html(e.target.files[0].name);
        }
    });
    </script>

{% endblock %}